import type { L3WorkforceRow } from "@/data/assess/types";
import type { CapabilityMapDefinition } from "@/data/capabilityMap/types";

/** Unified shape for the capability map view (L1 is in scopeName). */
export type MapViewL4 = { id: string; name: string };
export type MapViewL3 = { name: string; l4: MapViewL4[] };
export type MapViewL2 = { name: string; l3: MapViewL3[] };
export type CapabilityMapViewModel = {
  l1Name: string;
  secondaryLabel?: string;
  l2: MapViewL2[];
};

function norm(s: string): string {
  return s.trim().toLowerCase();
}

function l3Key(l2: string, l3: string): string {
  return `${norm(l2)}|${norm(l3)}`;
}

function slugify(s: string): string {
  return (
    s
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 24) || "x"
  );
}

/**
 * Infers L2 / L3 / L4 from uploaded footprint rows.
 *
 * The math now lives at L3 (one row per L2/L3), but each row may also carry a
 * display-only `l4Activities` list — either seeded from the canonical map,
 * generated by the LLM after upload, or populated from a legacy V3 import.
 * The view model exposes those activities as L4 leaves so the existing
 * `CapabilityMapPanel` tree continues to render unchanged.
 */
export function inferCapabilityViewFromRows(
  l1Name: string,
  rows: L3WorkforceRow[],
): CapabilityMapViewModel {
  const l2Order: string[] = [];
  const l2Map = new Map<string, Map<string, MapViewL3>>();

  for (const r of rows) {
    if (!l2Map.has(r.l2)) {
      l2Map.set(r.l2, new Map());
      l2Order.push(r.l2);
    }
    const m3 = l2Map.get(r.l2)!;
    let l3b = m3.get(r.l3);
    if (!l3b) {
      l3b = { name: r.l3, l4: [] };
      m3.set(r.l3, l3b);
    }
    const seenIds = new Set(l3b.l4.map((x) => x.id));
    const seenNames = new Set(l3b.l4.map((x) => x.name.toLowerCase()));
    if (Array.isArray(r.l4Activities)) {
      for (const name of r.l4Activities) {
        const trimmed = name.trim();
        if (!trimmed) continue;
        const lower = trimmed.toLowerCase();
        if (seenNames.has(lower)) continue;
        const id = `${r.id}::${slugify(trimmed)}`;
        if (seenIds.has(id)) continue;
        seenIds.add(id);
        seenNames.add(lower);
        l3b.l4.push({ id, name: trimmed });
      }
    }
  }

  return {
    l1Name,
    l2: l2Order.map((l2) => {
      const m3 = l2Map.get(l2)!;
      const l3s = Array.from(m3.values());
      return { name: l2, l3: l3s };
    }),
  };
}

export function definitionToViewModel(
  d: CapabilityMapDefinition,
  secondaryLabel?: string,
): CapabilityMapViewModel {
  return {
    l1Name: d.l1Name,
    secondaryLabel: secondaryLabel ?? d.name,
    l2: d.l2.map((l2) => ({
      name: l2.name,
      l3: l2.l3.map((l3) => ({
        name: l3.name,
        l4: l3.l4.map((l4) => ({ id: l4.id, name: l4.name })),
      })),
    })),
  };
}

/** Resolves a footprint row for a map L3: match by L2 + L3 name. */
export function findRowForMapL3(
  rows: L3WorkforceRow[],
  l2: string,
  l3: string,
): L3WorkforceRow | undefined {
  return rows.find((r) => l3Key(r.l2, r.l3) === l3Key(l2, l3));
}

export function isL3InFootprint(
  rows: L3WorkforceRow[],
  l2: string,
  l3: string,
): boolean {
  return findRowForMapL3(rows, l2, l3) !== undefined;
}
