import type { L3WorkforceRow } from "@/data/assess/types";
import type { CapabilityMapDefinition } from "@/data/capabilityMap/types";

/**
 * Unified shape for the capability-map view model (5-layer V5 capability
 * map). L1 is carried separately in `l1Name`; the panel renders the four
 * remaining layers as nested arrays:
 *
 *   view.l1Name   = L1 Function (tower)
 *   view.l2[]     = L2 Job Grouping
 *   view.l2[].l3  = L3 Job Family
 *   view.l3[].l4  = L4 Activity Group (the dial-bearing rung)
 *   view.l4[].l5  = L5 Activity (leaf — surfaced inside an Activity Group)
 *
 * Field NAMES (`l2` / `l3` / `l4` / `l5`) match the post-migration layer
 * numbering exactly so consumers don't have to keep a separate mental
 * mapping. The legacy `MapViewL4` type that historically pointed at the
 * leaf rung still exists as an alias — it now describes an Activity
 * Group; the actual leaf shape is `MapViewL5`.
 */
export type MapViewL5 = { id: string; name: string };
export type MapViewL4 = { id: string; name: string; l5: MapViewL5[] };
export type MapViewL3 = { name: string; l4: MapViewL4[] };
export type MapViewL2 = { name: string; l3: MapViewL3[] };
export type CapabilityMapViewModel = {
  l1Name: string;
  secondaryLabel?: string;
  l2: MapViewL2[];
};

function norm(s: string): string {
  return s.trim().toLowerCase();
}

function l3Key(l2: string, l3: string): string {
  return `${norm(l2)}|${norm(l3)}`;
}

function slugify(s: string): string {
  return (
    s
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 24) || "x"
  );
}

/**
 * Infers the 4-layer capability view (Job Grouping > Job Family > Activity
 * Group > Activity) from uploaded footprint rows. Each `L4WorkforceRow`
 * already pins one (l2, l3, l4) tuple — the dial-bearing Activity Group —
 * and may carry a display-only `l5Activities` list, either seeded from the
 * canonical map, generated by the LLM after upload, or populated from a
 * legacy import. The view model exposes those activities as L5 leaves
 * underneath the Activity Group rung.
 */
export function inferCapabilityViewFromRows(
  l1Name: string,
  rows: L3WorkforceRow[],
): CapabilityMapViewModel {
  const l2Order: string[] = [];
  const l2Map = new Map<string, Map<string, MapViewL3>>();

  for (const r of rows) {
    if (!l2Map.has(r.l2)) {
      l2Map.set(r.l2, new Map());
      l2Order.push(r.l2);
    }
    const m3 = l2Map.get(r.l2)!;
    let l3b = m3.get(r.l3);
    if (!l3b) {
      l3b = { name: r.l3, l4: [] };
      m3.set(r.l3, l3b);
    }
    // Dedupe Activity Groups within a Job Family — uploaded rows are
    // already 1:1 (l2/l3/l4), but defensive in case an upload shape
    // produces duplicates.
    let l4b = l3b.l4.find(
      (x) => x.name.toLowerCase() === (r.l4 ?? "").toLowerCase(),
    );
    if (!l4b) {
      l4b = { id: r.id, name: r.l4 ?? "", l5: [] };
      l3b.l4.push(l4b);
    }
    if (Array.isArray(r.l5Activities)) {
      const seenL5Names = new Set(l4b.l5.map((x) => x.name.toLowerCase()));
      for (const name of r.l5Activities) {
        const trimmed = name.trim();
        if (!trimmed) continue;
        const lower = trimmed.toLowerCase();
        if (seenL5Names.has(lower)) continue;
        seenL5Names.add(lower);
        l4b.l5.push({ id: `${r.id}::${slugify(trimmed)}`, name: trimmed });
      }
    }
  }

  return {
    l1Name,
    l2: l2Order.map((l2) => {
      const m3 = l2Map.get(l2)!;
      const l3s = Array.from(m3.values());
      return { name: l2, l3: l3s };
    }),
  };
}

export function definitionToViewModel(
  d: CapabilityMapDefinition,
  secondaryLabel?: string,
): CapabilityMapViewModel {
  return {
    l1Name: d.l1Name,
    secondaryLabel: secondaryLabel ?? d.name,
    l2: d.l2.map((l2) => ({
      name: l2.name,
      l3: l2.l3.map((l3) => ({
        name: l3.name,
        l4: l3.l4.map((l4) => ({
          id: l4.id,
          name: l4.name,
          l5: (l4.l5 ?? []).map((l5) => ({ id: l5.id, name: l5.name })),
        })),
      })),
    })),
  };
}

/** Resolves a footprint row for a map L3: match by L2 + L3 name. */
export function findRowForMapL3(
  rows: L3WorkforceRow[],
  l2: string,
  l3: string,
): L3WorkforceRow | undefined {
  return rows.find((r) => l3Key(r.l2, r.l3) === l3Key(l2, l3));
}

export function isL3InFootprint(
  rows: L3WorkforceRow[],
  l2: string,
  l3: string,
): boolean {
  return findRowForMapL3(rows, l2, l3) !== undefined;
}
