/**
 * Newline-delimited JSON event protocol for the v6 L3 initiative
 * curation streaming endpoint (`/api/assess/curate-l3-initiatives`).
 *
 * Mirrors the v5 `curateInitiativesStreamProtocol.ts` shape so the
 * `decodeStreamEvents` consumer is identical at the byte level — UI code
 * branches on `kind` and reads the v6-specific payload (`l3Initiatives`)
 * inside `row` events.
 *
 * Why streaming: a tower's L3 curation involves up to ~12 L3 Job
 * Families. Each per-L3 LLM call runs in 5-15s with reasoning effort.
 * A lockstep JSON response means the user stares at one spinner for
 * ~60-180s. The stream emits one `row` event per L3 as soon as it lands
 * so the Step 4 view re-renders progressively and the user sees
 * meaningful motion within the first 5-10s.
 *
 * Per-row atomic: each `row` event carries the COMPLETE list of 1-N AI
 * Solution initiatives for that L3 (not one event per initiative). The
 * orchestrator atomically replaces `L3WorkforceRowV6.l3Initiatives` in
 * one `setTowerAssess` call when the event lands so the cache key and
 * cache contents cannot drift.
 */

import type { L3Initiative } from "@/data/assess/types";

/** Per-row provenance — propagated to the client so the toolbar can
 *  show "n / m AI-curated · k fallback" while the stream is in flight. */
export type CurateL3RowSource = "llm" | "fallback";

/** Final source flag for the whole tower. `mixed` when at least one row
 *  fell back deterministically while at least one row succeeded via LLM. */
export type CurateL3OverallSource = "llm" | "fallback" | "mixed";

/**
 * One initiative as it crosses the wire. The full 4-lens `process` is
 * NOT included here — that's lazily generated by the deep-dive route on
 * first click, mirroring the v5 brief pattern. The orchestrator stamps
 * `id` server-side from `(towerId + l3RowId + slugified solutionName)`
 * so client and server agree on the stable id without a round-trip.
 */
export type CurateL3InitiativePayload = Omit<
  L3Initiative,
  "generatedProcess" | "source" | "generatedAt"
>;

export type CurateL3InitiativesStreamEvent =
  | {
      kind: "started";
      /** Number of input L3 rows the server is about to score. UI uses this
       *  to set up a progress bar and "n of m" countdown. */
      totalRows: number;
    }
  | {
      kind: "row";
      /** L3WorkforceRowV6 id this event corresponds to. */
      rowId: string;
      /** 1-N initiatives generated for this L3 (typically 1-3). */
      l3Initiatives: CurateL3InitiativePayload[];
      /** "llm" when the row came from the OpenAI call; "fallback" when
       *  the deterministic composer ran (per-row failure or no API key). */
      source: CurateL3RowSource;
      /** Per-row warning string (truncated server-side) — set when the
       *  LLM call for this row failed and the deterministic fallback ran
       *  instead, so the UI can flag "1 row used deterministic fallback". */
      warning?: string;
    }
  | {
      kind: "done";
      source: CurateL3OverallSource;
      /** Tower-level warning (e.g. "OPENAI_API_KEY not set") — distinct
       *  from per-row warnings; surfaces once at end of stream. */
      warning?: string;
    }
  | {
      kind: "error";
      /** Fatal error code — clients should stop reading after this event. */
      code:
        | "unauthorized"
        | "bad_request"
        | "payload_too_large"
        | "internal";
      message: string;
    };

/** Encode one event as a UTF-8 byte chunk for `ReadableStream.enqueue`. */
export function encodeL3StreamEvent(
  ev: CurateL3InitiativesStreamEvent,
): Uint8Array {
  return new TextEncoder().encode(JSON.stringify(ev) + "\n");
}

/**
 * Async iterator over a `Response.body` ReadableStream. Yields one
 * decoded event per yielded value. Mirrors `decodeStreamEvents` in the
 * v5 protocol — same semantics, distinct event union for v6.
 */
export async function* decodeL3StreamEvents(
  body: ReadableStream<Uint8Array>,
): AsyncGenerator<CurateL3InitiativesStreamEvent, void, void> {
  const reader = body.getReader();
  const decoder = new TextDecoder();
  let buffer = "";

  try {
    while (true) {
      const { value, done } = await reader.read();
      if (done) break;
      buffer += decoder.decode(value, { stream: true });

      let nlIdx = buffer.indexOf("\n");
      while (nlIdx !== -1) {
        const line = buffer.slice(0, nlIdx).trim();
        buffer = buffer.slice(nlIdx + 1);
        if (line) yield parseLine(line);
        nlIdx = buffer.indexOf("\n");
      }
    }
    const tail = buffer.trim();
    if (tail) yield parseLine(tail);
  } finally {
    reader.releaseLock();
  }
}

function parseLine(line: string): CurateL3InitiativesStreamEvent {
  let parsed: unknown;
  try {
    parsed = JSON.parse(line);
  } catch (e) {
    throw new Error(
      `Curate-L3 stream: malformed event line — ${(e as Error).message}`,
    );
  }
  if (!parsed || typeof parsed !== "object" || !("kind" in parsed)) {
    throw new Error("Curate-L3 stream: event missing `kind` field");
  }
  return parsed as CurateL3InitiativesStreamEvent;
}

/** MIME type the route emits and the client requests. */
export const CURATE_L3_STREAM_CONTENT_TYPE = "application/x-ndjson; charset=utf-8";

// ===========================================================================
//   Upload-initiatives enrichment protocol — sibling stream for the
//   "user supplies the list; LLM only enriches" path. Same NDJSON
//   envelope, distinct event union so the decoder branches by `kind`.
// ===========================================================================

/**
 * One enriched initiative on the wire. Uses the same `CurateL3InitiativePayload`
 * shape as the discovery stream so downstream rendering (`SolutionCardV2`,
 * `selectV6`) needs zero new types. The `matchedRowId` tells the orchestrator
 * which L3 row the initiative attaches to — either client-supplied (when
 * the upload matched an L3 by name) or LLM-picked (when the upload's L3
 * column was blank or unmatched).
 */
export type EnrichUploadInitiativePayload = CurateL3InitiativePayload;

export type EnrichUploadStreamEvent =
  | {
      kind: "started";
      /** Number of upload rows the server is about to enrich. */
      totalUploads: number;
    }
  | {
      kind: "row";
      /** Client-stable id echoed back so the orchestrator can reconcile. */
      uploadRowId: string;
      /** L3WorkforceRowV6 id this enriched initiative attaches to. */
      matchedRowId: string;
      /** One-sentence justification for the chosen L3 when the LLM auto-matched. */
      l3MatchRationale?: string;
      /** Single enriched initiative payload (always 1 per upload row). */
      payload: EnrichUploadInitiativePayload;
      /** "llm" when OpenAI was reached; "fallback" when the deterministic
       *  passthrough ran (no API key, per-row error, or timeout). The
       *  STORED `L3Initiative.source` stays "manual" either way because
       *  the human provided the seed — `source` here is wire-only. */
      source: CurateL3RowSource;
      /** Per-row warning string (truncated server-side). */
      warning?: string;
    }
  | {
      kind: "done";
      source: CurateL3OverallSource;
      /** Tower-level warning (e.g. "OPENAI_API_KEY not set"). */
      warning?: string;
    }
  | {
      kind: "error";
      code:
        | "unauthorized"
        | "bad_request"
        | "payload_too_large"
        | "internal";
      message: string;
    };

/** Encode one enrichment event as a UTF-8 byte chunk. */
export function encodeEnrichUploadStreamEvent(
  ev: EnrichUploadStreamEvent,
): Uint8Array {
  return new TextEncoder().encode(JSON.stringify(ev) + "\n");
}

/**
 * Async iterator over the enrichment stream body. Symmetric with
 * `decodeL3StreamEvents` — same buffering, distinct event union.
 */
export async function* decodeEnrichUploadStreamEvents(
  body: ReadableStream<Uint8Array>,
): AsyncGenerator<EnrichUploadStreamEvent, void, void> {
  const reader = body.getReader();
  const decoder = new TextDecoder();
  let buffer = "";

  try {
    while (true) {
      const { value, done } = await reader.read();
      if (done) break;
      buffer += decoder.decode(value, { stream: true });

      let nlIdx = buffer.indexOf("\n");
      while (nlIdx !== -1) {
        const line = buffer.slice(0, nlIdx).trim();
        buffer = buffer.slice(nlIdx + 1);
        if (line) yield parseEnrichLine(line);
        nlIdx = buffer.indexOf("\n");
      }
    }
    const tail = buffer.trim();
    if (tail) yield parseEnrichLine(tail);
  } finally {
    reader.releaseLock();
  }
}

function parseEnrichLine(line: string): EnrichUploadStreamEvent {
  let parsed: unknown;
  try {
    parsed = JSON.parse(line);
  } catch (e) {
    throw new Error(
      `Enrich-upload stream: malformed event line — ${(e as Error).message}`,
    );
  }
  if (!parsed || typeof parsed !== "object" || !("kind" in parsed)) {
    throw new Error("Enrich-upload stream: event missing `kind` field");
  }
  return parsed as EnrichUploadStreamEvent;
}

/** MIME type for the enrichment stream — same NDJSON envelope. */
export const ENRICH_UPLOAD_STREAM_CONTENT_TYPE =
  "application/x-ndjson; charset=utf-8";
