"use client";

import { getAssessProgram } from "@/lib/localStore";
import type { L4WorkforceRow, TowerId } from "@/data/assess/types";

/**
 * Tower workforce upload columns. The template carries L2 / L3 / L4 (Job
 * Grouping / Job Family / Activity Group) — L5 Activities are display-only
 * and either carried in capability-map definitions or generated by the LLM
 * after upload, so they don't appear here. Impact-lever percentages are also
 * intentionally absent: tower leads dial those on the Configure Impact
 * Levers page after the headcount lands.
 */
const HEADER = [
  "L2",
  "L3",
  "L4",
  "FTE_onshore",
  "FTE_offshore",
  "contractor_onshore",
  "contractor_offshore",
  "annual_spend_usd",
] as const;

/** Multiline CSV with header for one tower's current rows. */
export function buildAssessTowerCsv(rows: L4WorkforceRow[]): string {
  const lines = [HEADER.join(",")];
  for (const r of rows) {
    const esc = (x: string) => (x.includes(",") || x.includes('"') ? `"${x.replace(/"/g, '""')}"` : x);
    lines.push(
      [
        esc(r.l2),
        esc(r.l3),
        esc(r.l4),
        r.fteOnshore,
        r.fteOffshore,
        r.contractorOnshore,
        r.contractorOffshore,
        r.annualSpendUsd != null ? r.annualSpendUsd : "",
      ].join(","),
    );
  }
  return lines.join("\n");
}

export function downloadBlob(filename: string, content: string, mime: string): void {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

/**
 * Download the tower's *current* capability-map rows as CSV in the same
 * column shape the upload pipeline expects. Tower leads use this to grab a
 * working copy, edit values offline, and re-upload via Update map &
 * headcount — round-tripping cleanly with zero parser warnings.
 */
export function downloadCurrentTowerCapabilityMapCsv(towerId: TowerId, fileBase: string): void {
  const rows = getAssessProgram().towers[towerId]?.l4Rows ?? [];
  const csv = buildAssessTowerCsv(rows);
  downloadBlob(
    `${fileBase.replace(/[^a-z0-9-_]+/gi, "-")}-capability-map.csv`,
    csv,
    "text/csv;charset=utf-8",
  );
}
