-- Forge Assess: L3 Initiatives cutover (V5 -> V6).
--
-- Background:
--   The unit of analysis moves from L4 (Activity Group, dials + L5-grain
--   AI initiatives) up to L3 (Job Family, dials + 1-N specific AI Solution
--   products per L3). L4 rows remain in storage as read-only LLM context;
--   L5 leaves are dropped from runtime entirely (canonical map only).
--
--     - L3 Job Family    -> primary entity. Carries dials + AI Solutions.
--     - L4 Activity Group -> read-only context row. Headcount sums into L3.
--     - L5 Activity      -> retired from storage (canonical map keeps them
--                           as LLM prompt context).
--
-- Storage shape:
--   `assess_workshop.program` is JSONB; the schema itself is unchanged
--   (no new columns / indices / constraints). The migration is purely a
--   payload-level rewrite inside the JSONB document.
--
--   New `program.towers[towerId].l3Rows` array is the dial-bearing primary
--   entity. Existing `l4Rows` array is preserved verbatim as context (its
--   `offshoreAssessmentPct` / `aiImpactAssessmentPct` fields become
--   ignored by Step 2; the new dial values live on `l3Rows`).
--
--   Each `L3WorkforceRow` carries `l3Initiatives: L3Initiative[]` — the
--   1-N specific AI Solution products generated by the per-L3 LLM
--   pipeline. Each `L3Initiative` inlines a full 4-lens `Process` object.
--
-- Read-side compatibility:
--   The Next.js GET handler runs every loaded payload through
--   `importAssessProgramFromJsonText`, which carries V5 forward to V6:
--     1. Mirror the v5 blob to a backup record (one-shot, browser-side
--        only — server-side migration trusts the JSONB column itself).
--     2. Derive `l3Rows` from `l4Rows` via `deriveL3Rows()` (group by
--        l1/l2/l3, sum headcount + spend, leave dials undefined).
--     3. Drop v5 dials + `l5Items` + `l5Activities` from each l3 row's
--        derivation (they remain on `l4Rows` as legacy fields).
--     4. Mark every derived `l3Row.curationStage = "queued"` so the
--        StaleCurationBanner invites the user to re-run curation.
--   The PUT handler enforces `version === 6` once the v6 deploy is live.
--
-- This script:
--   1. Updates the table COMMENT so a fresh `\d+ assess_workshop` reports
--      the current contract.
--   2. Backfills `program.version` from 5 (or anything < 6) to 6 in place
--      so the stored payload's reported version matches the runtime
--      contract. Field-level derivation is intentionally NOT done in SQL —
--      the read-time migration in `localStore.migrateAssessProgram` /
--      `assessProgramIO.importAssessProgramFromJsonText` is the single
--      source of truth and runs again on the next read regardless.
--   3. Idempotent: re-running this migration on V6 rows is a no-op.
--
-- Cutover playbook (manual):
--   1. Apply this script against the dev DB first; verify GET /api/assess
--      returns the migrated payload.
--   2. Walk Steps 1, 2, 4 on Finance in dev to confirm: l4 upload still
--      works, derived l3Rows render in Step 2, curation refresh produces
--      named AI Solutions in Step 4.
--   3. Cut the `main` branch deploy to production with
--      NEXT_PUBLIC_FORGE_SCHEMA=v6; the v6 code re-runs the read-time
--      migration on every GET so any v5 row that landed during the
--      rollout window is silently upgraded on first load.
--   4. Apply this script against production AFTER the v6 deploy is live.
--      Order matters: applying it before the deploy would let v5 code see
--      `version: 6` and reject the payload with "version must be 5."
--
-- Rollback:
--   The browser-side mirror at `forge.assessProgram.preMigration.<iso>`
--   in localStorage retains the pre-cutover v5 blob for 30 days. To
--   restore one user's v5 state, see the runbook in
--   `docs/cutover-l3-initiatives.md`.

BEGIN;

UPDATE assess_workshop
   SET program = jsonb_set(program, '{version}', to_jsonb(6))
 WHERE COALESCE((program->>'version')::int, 0) < 6;

COMMENT ON TABLE assess_workshop IS
  'Stores AssessProgramV6 JSON for the /assess product (L3-grain initiatives: L1 Function / L2 Job Grouping / L3 Job Family with dials + AI Solutions / L4 Activity Group as read-only context / L5 retired from storage). One row per workshop; default id is "default". Migration from V5 happens at read time in importAssessProgramFromJsonText.';

COMMIT;
