/**
 * Glossary data — single source of truth for both:
 *   1. The full glossary page at `/glossary` (renders the array, grouped by category)
 *   2. The inline <Term /> tooltips used throughout the app
 *
 * Each entry has an `id` (URL anchor + stable key for tooltips), a category, a
 * term label, a one-liner (`short`), and an optional `long` description.
 *
 * `getGlossaryEntry()` is the case-insensitive lookup used by <Term />; it
 * matches against `id` and `term`.
 */

export type GlossaryCategory =
  | "Operating model"
  | "Agents & architecture"
  | "Prioritisation & delivery"
  | "People & change";

export type GlossaryEntry = {
  id: string;
  category: GlossaryCategory;
  term: string;
  short: string;
  long?: string;
};

export const glossary: GlossaryEntry[] = [
  // ---- Operating model -------------------------------------------------
  {
    id: "l1",
    category: "Operating model",
    term: "L1 — Function",
    short: "The tower itself — Finance, HR, Editorial News, etc.",
    long: "Level-1 of the 5-layer Versant capability map. One L1 per tower; everything else hangs under it.",
  },
  {
    id: "l2",
    category: "Operating model",
    term: "L2 — Job Grouping",
    short: "Top-level grouping inside a tower.",
    long: "Level-2 of the capability map. Groups related Job Families under the tower function — e.g. 'Operate', 'Govern', 'Build'. Used to anchor cross-tower comparisons; not directly scored.",
  },
  {
    id: "l3",
    category: "Operating model",
    term: "L3 — Job Family",
    short: "Functional family of work — what a director or VP runs.",
    long: "Level-3 of the capability map. Examples: 'Talent Acquisition' inside HR, 'Treasury' inside Finance. Job Families group several Activity Groups; they are the natural unit for organisational discussion but the dial is set one rung deeper at L4.",
  },
  {
    id: "l4",
    category: "Operating model",
    term: "L4 — Activity Group",
    short: "Activity bundle inside a Job Family. The unit we score for offshore + AI.",
    long: "Level-4 of the capability map. Activity Groups are the grain captured in the program — headcount lives here and the offshore + AI dials are applied here. Example: 'Sourcing & Screening' inside 'Talent Acquisition'.",
  },
  {
    id: "l5",
    category: "Operating model",
    term: "L5 — Activity",
    short: "Concrete activity under an Activity Group. Where AI initiatives attach.",
    long: "Level-5 of the capability map. L5 Activities are the leaf-level tasks — what a person actually does day-to-day. They are seeded from the canonical map or generated by the LLM after upload, and they're the rung the AI initiative cards score for ship-readiness.",
  },
  {
    id: "capability-map",
    category: "Operating model",
    term: "Capability map",
    short: "The 5-layer (L1-L5) hierarchy that describes what a tower does.",
    long: "Capability maps are authored once per tower as Function > Job Grouping > Job Family > Activity Group > Activity. The dial pair (offshore + AI) sits at L4 Activity Group; AI initiatives attach at L5 Activity. The hierarchy is the canonical structure every step of the program scores against.",
  },
  {
    id: "fte",
    category: "Operating model",
    term: "FTE",
    short: "Full-time equivalent — one person at standard hours.",
    long: "We track FTE separately from contractors so the headcount reflects Versant's actual hire mix.",
  },
  {
    id: "contractor",
    category: "Operating model",
    term: "Contractor",
    short: "Non-FTE labour — agency, vendor, or per-project staff.",
    long: "Tracked separately from FTE because contractor cost-to-serve and offshorability often differ.",
  },

  // ---- Prioritisation & delivery --------------------------------------
  {
    id: "offshore-dial",
    category: "Prioritisation & delivery",
    term: "Offshore dial",
    short: "0-100 share of an L4 Activity Group that could plausibly move offshore.",
    long: "Captures the editorial / news / political-brand sensitivity of the work, the location requirement, and the complexity. Defaults seeded from heuristics; tower leads override per L4 Activity Group.",
  },
  {
    id: "ai-impact-dial",
    category: "Prioritisation & delivery",
    term: "AI impact dial",
    short: "0-100 estimate of AI-driven automation or augmentation headroom for the L4 Activity Group.",
    long: "Combines task structuredness, data availability, and review burden. Defaults seeded from heuristics; tower leads override per L4 Activity Group. Read alongside the AI Initiatives module for the agents that realise this headroom.",
  },
  {
    id: "baseline",
    category: "Prioritisation & delivery",
    term: "Baseline",
    short: "The tower-level offshore + AI starting point used in roll-ups.",
    long: "When an L4 Activity Group has no specific dial, the tower baseline is used in weighted summaries so every tower contributes a number rather than a blank.",
  },
  {
    id: "scenario",
    category: "Prioritisation & delivery",
    term: "Scenario",
    short: "A stress-test of the baseline on the summary page.",
    long: "Scenarios let you push the dials beyond the program baseline (for executive what-ifs) without overwriting the per-L4 inputs.",
  },
  {
    id: "feasibility",
    category: "Prioritisation & delivery",
    term: "Feasibility (Ship-ready / Investigate)",
    short: "Per-L5 Activity ship-readiness signal — set on each tower's Step 4.",
    long: "Binary signal on every AI-eligible L5 Activity. Ship-ready = leverages a proven Versant platform or pattern (BlackLine, Eightfold, Amagi, Workday, etc.) and can land in the first half-year. Investigate = needs new platform stand-up, deeper integration, or heavier change management. Feasibility is a tower-level signal only — it never sets program priority.",
  },
  {
    id: "priority-tier",
    category: "Prioritisation & delivery",
    term: "Program priority tier (P1 / P2 / P3 / Deprioritized)",
    short: "Where an AI initiative lands in the cross-tower 2x2.",
    long: "Set on the Cross-Tower AI Plan by the deterministic 2x2 over feasibility × parent-L4 Activity Group business impact: P1 — Quick Wins (HF · HBI), shipped first. P2 — Fill-ins (HF · LBI), slotted in around the Quick Wins. P3 — Strategic Builds (LF · HBI), longer build runway for high-prize programs. Deprioritized (LF · LBI) sits below the line — visible for context but excluded from the active plan. P-tiers also drive Gantt staging (M1 / M7 / M13).",
  },
  {
    id: "plan-threshold",
    category: "Prioritisation & delivery",
    term: "Plan threshold (minimum L4 Activity Group prize)",
    short: "Secondary cross-tower filter — the minimum parent-L4 Activity Group prize for inclusion.",
    long: "After the 2x2 splits initiatives into P1 / P2 / P3 / Deprioritized, the plan threshold runs on top: an L5 Activity initiative stays in plan only when its parent L4 Activity Group's full aiUsd clears the threshold. Operates at the same grain as the 2x2 (L4 prize), not the per-L5 attribution, so it doesn't double-jeopardise P2 rows whose per-L5 split is small by definition. Default $1M (matches the 2x2 floor). Below-threshold initiatives are surfaced as opportunistic and addressed inside the tower roadmaps.",
  },
  {
    id: "impact-tier",
    category: "Prioritisation & delivery",
    term: "Impact tier",
    short: "Qualitative size of opportunity — High / Medium / Low.",
    long: "We use tiers, not point estimates. High / Medium / Low capture the qualitative size of the opportunity. Discovery refines specific numbers.",
  },

  // ---- Agents & architecture ------------------------------------------
  {
    id: "agent",
    category: "Agents & architecture",
    term: "Agent",
    short: "A persistent AI worker with a role, tools, and guardrails.",
    long: "Each agent has a defined role (Specialist / Monitor / Router / Executor / Orchestrator), the tools it can use, the guardrails on its actions, and the metric it's optimising. Agents in this portal are designed for human review on consequential outputs.",
  },
  {
    id: "orchestrator",
    category: "Agents & architecture",
    term: "Orchestrator",
    short: "The top-level agent that routes work to specialists.",
    long: "Reads the inbound request, decides which downstream agent or tool runs, and is the point where humans intervene if confidence is low.",
  },
  {
    id: "specialist",
    category: "Agents & architecture",
    term: "Specialist",
    short: "Domain-focused agent — owns a narrow, well-defined task.",
    long: "Examples: a Reconciliation specialist for finance close, a Captioning specialist for editorial. Specialists are the unit of swap-out as models improve.",
  },
  {
    id: "guardrail",
    category: "Agents & architecture",
    term: "Guardrail",
    short: "A rule the agent must satisfy before acting.",
    long: "Includes confidence thresholds, prohibited content categories, dollar limits, mandatory human review steps, and audit logging. Guardrails are how the platform stays safe at scale.",
  },

  // ---- People & change -------------------------------------------------
  {
    id: "persona",
    category: "People & change",
    term: "Persona",
    short: "Who you are in the program — Versant lead, Accenture lead, or executive.",
    long: "Determines the home-page CTA, default views, and which collaboration surfaces are available to you.",
  },
  {
    id: "tower-lead",
    category: "People & change",
    term: "Tower lead",
    short: "The person responsible for a tower's content and dials.",
    long: "Tower leads upload the L1-L4 capability map and headcount, set offshore + AI dials per L4 Activity Group, and sign the tower off as reviewed when it is ready for the rollup. The L5 Activity layer is generated by the LLM after upload.",
  },
  {
    id: "tsa",
    category: "People & change",
    term: "TSA",
    short: "Transition Services Agreement with NBCUniversal.",
    long: "Versant runs on NBCU shared services until the TSA expires; many of the new initiatives in this portal are about preparing for that transition (ad sales, finance close, IT, security).",
  },
];

// ---------- Inline-tooltip lookup ---------------------------------------

const ENTRY_BY_KEY = (() => {
  const map: Record<string, GlossaryEntry> = {};
  for (const e of glossary) {
    map[e.id.toLowerCase()] = e;
    map[e.term.toLowerCase()] = e;
  }
  return map;
})();

export function getGlossaryEntry(term: string): GlossaryEntry | null {
  if (!term) return null;
  return ENTRY_BY_KEY[term.trim().toLowerCase()] ?? null;
}

export function listGlossaryEntries(): GlossaryEntry[] {
  return [...glossary];
}

/**
 * Legacy alias used by `<TermTip />`. Prefer `getGlossaryEntry()`.
 */
export const findTerm = getGlossaryEntry;
